### ISSUE TITLE
Request: Album downloading

### ISSUE THREAD

**Issue by trustosas** [devlocalhost/pyspodl#2]
Title says it all. I don't know how difficult this will be to implement, but I'd appreciate it

**Comment by devlocalhost** [comment]
Its not difficult. All i (probably) need to do is get album ID, then get the songs (of the album) ID, and download them. The problem is, my laptop isn't working (won't charge, charger isn't working), so this will probably take some time (since ill have to do it on my phone). Ill let you know when I'm done

**Comment by trustosas** [comment]
I know a bit of python and I'm looking to learn how the program works soon. If you can provide a little guidance on how it works I could contribute in the future hopefully.
Consider making a backup of this repo too. Spotify is pretty trigger happy on these kinds of stuff.

**Comment by devlocalhost** [comment]
> I know a bit of python and I'm looking to learn how the program works soon. If you can provide a little guidance on how it works I could contribute in the future hopefully. Consider making a backup of this repo too. Spotify is pretty trigger happy on these kinds of stuff.

You can go ahead and take a look at the source code if you want to improve something. And what do you mean by "how it works"? 

How it downloads the song? It uses a library called "librespot" (link in readme)

How it gets playlist data/songs? It uses the Spotify web api, using the requests module. Then i format the output the api gives (which is in json)

Ohh, and one thing, the code is a mess. The variable names, the functions, etc. It can be improved, but it's kinda difficult right now, because I can't use my laptop. I will try to improve it, but slowly

**Comment by devlocalhost** [comment]
![Screenshot_20220801-174314_Pydroid 3](https://user-images.githubusercontent.com/56504654/182177085-cdcd6777-ea89-4a78-9078-6135126699d1.png)
Update: I was right. It's basically the same as the "playlist_info" and probably "playlist_download" functions. I will keep testing and see

**Comment by devlocalhost** [comment]
![Screenshot_20220801-180514_Termux](https://user-images.githubusercontent.com/56504654/182180279-679c812f-8876-44f6-a979-4d178f92d58d.png)

**Comment by devlocalhost** [comment]
Well that was easy. It was copy pasting actually, just a few changes. I've not tested it properly tho. But its working, no issues. Do you want me to push, or should I keep testing and make some fixes for a few days?

![Screenshot_20220801-181913_Termux](https://user-images.githubusercontent.com/56504654/182183187-581a803d-243b-4133-a9ac-629f548a9904.png)
![Screenshot_20220801-181917_Termux](https://user-images.githubusercontent.com/56504654/182183198-e9c3e042-cd09-4859-b895-a6d7e4d86a5e.png)

**Comment by trustosas** [comment]
Keep testing :)  better safe than sorry

**Comment by devlocalhost** [comment]
This feature will be pushed in August 12
